image:
   name: hashicorp/terraform:light
   entrypoint:
     - '/usr/bin/env'
     - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_PIPELINE_SOURCE == "push"
      when: never
    - when: always

stages:
  - tf-init
  - tf-validate
  - tf-plan
  - tf-apply

tf-init:
  stage: tf-init
  script:
    - rm -rf ./tf/.terraform
    - mkdir -p ./tf/gcp
    - echo $GOOGLE_CREDENTIALS_B64 | base64 -d > ./tf/gcp/key-file.json
    - cd ./tf && terraform init
  artifacts:
    paths:
      - ./tf/gcp/*
      - ./tf/.terraform/*
      - ./tf/.terraform.lock.*

tf-plan:
  stage: tf-plan
  dependencies:
    - tf-init
  script:
    - ls -ltr ./tf
    - cd ./tf && terraform validate && terraform plan -out "tf-plan"
  artifacts:
    paths: 
      - ./tf/tf-plan
